### ISSUE TITLE
Is it possible to use the new version of Edge browser to replace Chrome?

### ISSUE THREAD

**Issue by blakebill** [ReekyStive/daily-reporter#3]
Edge also provides [Webdriver](https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/) and the new version of Edge Browser has a good  compatibility with windows.

**Comment by lennondotw** [comment]
Sure. Added to TODO list.

**Comment by reekystive** [comment]
Hi! I'm glad to tell you I have added support for Microsoft Edge and Firefox: 5d074eb

There's also a new release: [v1.5](https://github.com/reekystive/daily-reporter/releases/tag/v1.5)

I'm going to close this issue.

**Comment by lennondotw** [comment]
Hi! I'm glad to tell you I have added support for Microsoft Edge and Firefox: 5d074eb

There's also a new release: [v1.5](https://github.com/reekystive/daily-reporter/releases/tag/v1.5)

I'm going to close this issue.

**Comment by mikojelena** [comment]
mua，I will try it！

ReekyStive ***@***.***> 于 2021年11月13日周六 20:04写道：
